### ISSUE TITLE
show events and availability for another person's calendar

### ISSUE THREAD

**Issue by flavorjones** [flavorjones/calendar-assistant#36]
hanging off #18 

- [x] show availability for another calendar
- [x] show events for another calendar
- [x] make sure time zones are handled appropriately (see below)
- [x] make sure print_events and print_available_blocks show the right header info (from the right calendar)
- [x] investigate whether free/busy is right for unresponded-to events?

consider whether attributes should be on CA or on EventRepository (e.g., calendar) and whether the "default" for CA should change if only one required attendee is present

**Comment by flavorjones** [comment]
wrt time zones, check it:

```
$ be ruby -Ilib bin/calendar-assistant avail -r mkocher@pivotal.io
mdalessio@pivotal.io
- all times in America/New_York
- looking for blocks at least 30 mins long
- between 9am and 6pm in America/New_York

Availability on Wednesday, November 7:

 • 9:00am - 11:30am
 • 3:00pm - 2:00pm
 • 5:25pm - 6:00pm


$ be ruby -Ilib bin/calendar-assistant avail -r mkocher@pivotal.io -z America/Los_Angeles
mdalessio@pivotal.io
- all times in America/New_York
- looking for blocks at least 30 mins long
- between 9am and 6pm in America/Los_Angeles

Availability on Wednesday, November 7:

 • 12:00pm - 11:30am
 • 3:00pm - 2:00pm
 • 5:25pm - 3:00pm
 • 7:30pm - 9:00pm
```

**Comment by flavorjones** [comment]
Closing this, merged #43. See #44 for some outstanding issues, though.
